-- Active: 1776911206189@@tzyzt3017-dtvy3017.h.aivencloud.com@22257@mysql

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_type ENUM('VNU', 'Other') NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)