CREATE TABLE users IF NOT EXISTS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	user_type ENUM('VNU', 'Other') NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
